# Generated by Django 3.1.7 on 2021-03-08 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210308_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='badges',
            field=models.CharField(default='', max_length=100),
        ),
    ]
