# Generated by Django 3.1.7 on 2021-03-10 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_badges'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='challenge_streak',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='customuser',
            name='max_challenge_streak',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
