# Generated by Django 3.1 on 2021-03-17 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(default='A very good title', max_length=50)),
                ('category', models.CharField(max_length=30)),
                ('correct_answer', models.PositiveIntegerField(default=1)),
                ('description', models.TextField()),
            ],
        ),
    ]
